budgetbuddy/account/urls.py
from django.urls import path

from account.views import *

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    #report
    path('transaction/', TransactionView.as_view(), name="transaction"),
    path('transaction/delete/<int:transaction_id>/', TransactionView.as_view(), name="transaction"),
    path('transaction/add/', AddTransactionView.as_view(), name="addTransaction"),
    path('transaction/edit/<int:transaction_id>/', EditTransactionView.as_view(), name="editTransaction"),
    #budget
    path('budget/', BudgetView.as_view(), name="budget"),
    path('budget/delete/<int:budget_id>/', BudgetView.as_view(), name="deleteBudget"),
    path('budget/add/', AddBudgetView.as_view(), name="addBudget"),
    path('budget/edit/<int:budget_id>/', EditBudgetView.as_view(), name="editBudget"),
    #saving
    path('saving/', SavingView.as_view(), name="saving"),
    path('saving/delete/<int:saving_id>/', SavingView.as_view(), name="deleteSaving"),
    path('saving/add/', AddSavingView.as_view(), name="addSaving"),
    path('saving/edit/<int:saving_id>/', EditSavingView.as_view(), name="editSaving"),
    #account
    path('account/', AccountView.as_view(), name="account"),
    path('account/add/', AddAccountView.as_view(), name="addAccount"),
    path('account/delete/<int:account_id>/', AccountView.as_view(), name="deleteAccount"),
    path('account/edit/<int:account_id>/', EditAccountView.as_view(), name="editAccount"),
    #notify
    path('notify/', NotifyView.as_view(), name="notify"),
    path('notify/delete/<int:notification_id>/', NotifyView.as_view(), name="deleteNotify"),
    
    #Edit Profile
    path('editprofile/', EditProfileView.as_view(), name="edit-profile"),
    path('editprofile/resetpassword', ResetPassWordView.as_view(), name="reset-password"),
    
    # dev zone
    ## categories
    path('developer/categories/', CategoriesDevView.as_view(), name="categoriesDev"),
    path('developer/categories/delete/<int:category_id>/', CategoriesDevView.as_view(), name="deleteCategoryDev"),
    path('developer/categories/add', AddCategoriesDevView.as_view(), name="addCategoriesDev"),
    path('developer/categories/edit/<int:category_id>/', EditCategoriesDevView.as_view(), name="editCategoryDev"),
    ## tags
    path('developer/tags/', TagsDevView.as_view(), name="tagsDev"),
    path('developer/tags/delete/<int:tag_id>/', TagsDevView.as_view(), name="deleteTagDev"),
    path('developer/tags/add', AddTagsDevView.as_view(), name="addTagsDev"),
    path('developer/tags/edit/<int:tag_id>/', EditTagsDevView.as_view(), name="editTagDev"),
    ## staff
    path('developer/staffs/', StaffDevView.as_view(), name="staffDev"),
    path('developer/staffs/add/<int:user_id>/', StaffDevView.as_view(), name="addStaffDev"),
    path('developer/staffs/delete/<int:user_id>/', StaffDevView.as_view(), name="delStaffDev"),

    #PDF FILE
    path('monthlyreport/', ViewPDF.as_view(), name="monthly-report"),
]

budgetbuddy/authen/urls.py
from django.urls import path

from authen.views import LoginView, LogoutView, RegisterView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users_hub/password_reset.html"), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="users_hub/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users_hub/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users_hub/password_reset_complete.html'), name='password_reset_complete'),
]

budgetbuddy/budgetbuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/', include('authen.urls')),
    path('account/', include('account.urls')),
    path('', IndexView.as_view(), name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budgetbuddy/account/models.py
from django.db import models
from django.contrib.auth.models import User  # Using Django's built-in user model for authentication

class Account(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('income', 'Income'),
        ('expense', 'Expense')
    ]

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    create_at = models.DateTimeField(auto_now_add=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    transaction_type = models.CharField(max_length=7, choices=TRANSACTION_TYPES)
    tags = models.ManyToManyField(Tag, blank=True, null=True)

    def __str__(self):
        return f'{self.transaction_type.capitalize()} - {self.amount}'

class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Budget for {self.category}'

class SavingsGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    target_amount = models.DecimalField(max_digits=10, decimal_places=2)
    current_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    target_date = models.DateField()

    def __str__(self):
        return self.name

class Notification(models.Model):
    TRANSACTION_TYPES = [
        ('50b', '50% Budget Used'),
        ('75b', '75% Budget Used'),
        ('100b', '100% Budget Used'),
        ('100s', '100% Saving Goal'),
        ('7ds', '7 Day Left Saving Goal'),
        ('1ds', '1 Day Left Saving Goal'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notify_type = models.CharField(max_length=25, choices=TRANSACTION_TYPES)
    message = models.TextField()
    notification_date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'Notification for {self.user}'

budgetbuddy/account/views.py
from .forms import *
from account.models import *
from django.db.models import *
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User, Group
from django.core.paginator import Paginator
from django.db.models.functions import TruncMonth
from datetime import datetime, timedelta
from django.utils import timezone
from .notifications import Notify
from django.contrib import messages
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from authen.models import ProfilePicture

#Opens up page as PDF
class ViewPDF(LoginRequiredMixin, View):
    login_url = "/authen/"
    def render_to_pdf(self, template_src, context_dict={}):
        template = get_template(template_src)
        html = template.render(context_dict)
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
        if not pdf.err:
            return HttpResponse(result.getvalue(), content_type='application/pdf')
        return None
    
    def get(self, request, *args, **kwargs):
        user_pk = request.user.pk
        user_accounts = request.user.account_set.all()
        user = User.objects.get(pk=user_pk)
        month_report = request.GET.get('month-report')
    
        if month_report:
            # แยก year และ month ออกจากค่า month-report
            year, month = map(int, month_report.split('-'))
        else:
            # ถ้าไม่มีค่า month-report ใช้ค่า year และ month ปัจจุบัน
            year = timezone.now().year
            month = timezone.now().month

        # แปลงปีและเดือนให้เป็น integer
        year = int(year)
        month = int(month)

        if month < 1 or month > 12:
            return HttpResponse("Invalid month", status=400)

        # คำนวณยอดรวมรายรับของเดือนที่เลือก
        total_income_current = Transaction.objects.filter(
            account__in=user_accounts,
            create_at__year=year,
            create_at__month=month,
            transaction_type='income'
        ).aggregate(sum_income=Sum('amount'))['sum_income'] or 0
        
        # คำนวณยอดรวมรายจ่ายของเดือนที่เลือก
        total_expense_current = Transaction.objects.filter(
            account__in=user_accounts,
            create_at__year=year,
            create_at__month=month,
            transaction_type='expense'
        ).aggregate(sum_expense=Sum('amount'))['sum_expense'] or 0

        this_month_income = []
        
        # ถ้ามีรายรับ คำนวณรายรับต่อหมวดหมู่
        if total_income_current > 0:
            this_month_income = Transaction.objects.filter(
                account__in=user_accounts,
                create_at__year=year,
                create_at__month=month,
                transaction_type='income'
            ).values('category__name').annotate(
                total_income=Sum('amount')
            ).annotate(
                income_percent=(F('total_income') / total_income_current) * 100
            ).order_by('income_percent')

        this_month_expense = []
        
        # ถ้ามีรายจ่าย คำนวณรายจ่ายต่อหมวดหมู่
        if total_expense_current > 0:
            this_month_expense = Transaction.objects.filter(
                account__in=user_accounts,
                create_at__year=year,
                create_at__month=month,
                transaction_type='expense'
            ).values('category__name').annotate(
                total_expense=Sum('amount')
            ).annotate(
                expense_percent=(F('total_expense') / total_expense_current) * 100
            ).order_by('expense_percent')

        context = {
            'user': user,
            'create_at': timezone.now(),  # ใช้เวลาปัจจุบันสำหรับการสร้าง PDF
            'this_month_income': this_month_income,
            'this_month_expense': this_month_expense,
            'total_income_current': total_income_current,
            'total_expense_current': total_expense_current,
            'selected_year': year,
            'selected_month': month,
        }
        
        # สร้าง PDF
        pdf = self.render_to_pdf('pdf/monthlyreport.html', context)
        return HttpResponse(pdf, content_type='application/pdf')

class IndexView(View):
    def get(self, request):
        return render(request, 'index.html', {
            'request': request,
            'path': request.path
        })

class HomeView(LoginRequiredMixin, View):
    login_url = "/authen/"
    def ensure_six_elements(self, data_list):
        # ตรวจสอบว่า list มีสมาชิกครบ 6 ตัวมั้ย
        while len(data_list) < 6:
            data_list.insert(0, 0.0) 
        return data_list
    
    def get(self, request):
        user_pk = request.user.pk
        user_accounts = request.user.account_set.all()
        user = User.objects.get(pk=user_pk)
        profile_picture, created = ProfilePicture.objects.get_or_create(user=user)
        selected_account_id = request.GET.get('account', 'all')
        search_description = request.GET.get('search', '')
        
        #check get account id กัน user ดูข้อมูลคนอื่น
        user_account_ids = [key.id for key in user_accounts]
        if selected_account_id != 'all' and int(selected_account_id) not in user_account_ids:
            selected_account_id = 'all'

        print(selected_account_id)
        # คำนวณรายรับรายจ่ายรวมของ user
        user_income = Transaction.objects.filter(account__in=user_accounts, transaction_type='income').aggregate(total_income=Sum('amount'))
        user_expense = Transaction.objects.filter(account__in=user_accounts, transaction_type='expense').aggregate(total_expense=Sum('amount'))
        total_income = user_income['total_income'] or 0
        total_expense = user_expense['total_expense'] or 0
        
        # คำนวณจำนวน savingGoals และ Budget ที่ user ได้สร้างเอาไว้
        user_savinggoals = SavingsGoal.objects.filter(user_id=user_pk).aggregate(count_saving=Count('id'))
        user_budget = Budget.objects.filter(user_id=user_pk).aggregate(count_budget=Count('id'))
        total_savinggoals = user_savinggoals['count_saving'] or 0
        total_budget = user_budget['count_budget'] or 0
        
        # query transaction ของ user นี้ตาม selected account
        user_transactions = Transaction.objects.filter(account__in=user_accounts).order_by('-create_at', '-transaction_type')
        
        if selected_account_id and selected_account_id != 'all':
            user_transactions = Transaction.objects.filter(account_id=selected_account_id).order_by('-create_at', '-transaction_type')
        if search_description:
            user_transactions = user_transactions.filter(
                Q(description__icontains=search_description) |
                Q(category__name__icontains=search_description) |
                Q(tags__name__icontains=search_description)
            )
            
        paginator = Paginator(user_transactions, 6)
        page_number = request.GET.get('page')
        transactions_list = paginator.get_page(page_number)
        
        # ทำส่วนของกราฟเส้น
        # คำนวณช่วง 6 เดือนที่ผ่านมา
        six_months_ago = datetime.now() - timedelta(days=6*30)

        # Query รายรับในแต่ละเดือน
        six_month_income = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__gte=six_months_ago, transaction_type='income')
            .annotate(month=TruncMonth('create_at'))
            .values('month')
            .annotate(total_income=Sum('amount'))
            .order_by('month')
        )
        graph_total_income = self.ensure_six_elements([float(income['total_income']) for income in six_month_income])
        print(six_month_income)
        # Query รายจ่ายในแต่ละเดือน
        six_month_expense = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__gte=six_months_ago, transaction_type='expense')
            .annotate(month=TruncMonth('create_at'))
            .values('month')
            .annotate(total_expense=Sum('amount'))
            .order_by('month')
        )
        graph_total_expense = self.ensure_six_elements([float(expense['total_expense']) for expense in six_month_expense])
        
        six_month_expense_avg = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__gte=six_months_ago, transaction_type='expense')
            .annotate(month=TruncMonth('create_at'))
            .values('month')
            .annotate(total_expense=Sum('amount'))
            .aggregate(average_expense=Avg('total_expense'))
        )
        
        six_month_income_avg = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__gte=six_months_ago, transaction_type='income')
            .annotate(month=TruncMonth('create_at'))
            .values('month')
            .annotate(total_income=Sum('amount'))
            .aggregate(average_income=Avg('total_income'))
        )
        
        #ส่วนของกราฟโดนัท
        current_month_income_sum = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__month=datetime.now().month, create_at__year=datetime.now().year, transaction_type='income')
            .aggregate(sum_income=Sum('amount'))
        )
        if current_month_income_sum['sum_income'] is None:
            current_month_income_sum['sum_income'] = 0
        
        current_month_expense_sum = (
            Transaction.objects
            .filter(account__in=user_accounts, create_at__month=datetime.now().month, create_at__year=datetime.now().year, transaction_type='expense')
            .aggregate(sum_expense=Sum('amount'))
        )
        if current_month_expense_sum['sum_expense'] is None:

budgetbuddy/account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="x-icon" href="{% static 'image/logo.jpg' %}" />
    <title>{% block title %}Title{% endblock %}</title>
</head>

<body class="text-gray-800 font-inter">
    {% block nav %}
    {% include 'sidebar.html' %}
    {% endblock %}
    
    {% block content %}
    {% endblock %}
    
    {% block scripts %}
    {% endblock %}

</body>

</html>

budgetbuddy/account/templates/notify.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Saving{% endblock %}

{% block content %}
 
<main class="w-full md:w-[calc(100%-256px)] md:ml-64 bg-gray-50 min-h-screen transition-all main">
    <div class="py-2 px-6 bg-white flex items-center shadow-md shadow-black/5 sticky top-0 left-0 z-30 pt-3 pb-3">
        <ul class="flex items-center text-sm ml-4">
            <li class="mr-2">
                <a href="{% url 'home' %}" class="text-gray-400 hover:text-gray-600 font-medium">BudgetBuddy</a>
            </li>
            <li class="text-gray-600 mr-2 font-medium">/</li>
            <li class="text-gray-600 mr-2 font-medium">Notify</li>
        </ul>
    </div>
    
    {% for notification in notifications %}
        <div class="pt-4 pl-4 pr-4">
            <div class="bg-white rounded-md border border-gray-100 p-6 shadow-md shadow-black/5 w-full">
                <div class="flex justify-between mb-6">
                    <div class="w-full">
                        <div class="flex justify-between ">
                            {% if notification.category.name == "SavingGoals" %}
                                <div class="text-2xl font-semibold mb-1">{{ notification.name }}: {{ notification.notify_type }}</div>
                            {% else %}
                            <div class="text-2xl font-semibold mb-1">{{ notification.category }}: {{ notification.notify_type }}</div>
                            {% endif %}
                            <div class="flex text-2xl mb-1">
                                <div class="text-sm font-medium text-gray-400 flex items-center">
                                    {{ notification.notification_date|date:"M. d, Y, h:i A" }}
                                </div>
                                <button type="button" onclick="deleteNotification({{ notification.id }}, '{{csrf_token}}')" class="ml-5 delete flex items-center text-gray-600 hover:text-blue-500 hover:bg-gray-50">
                                    <i class="ri-close-line"></i>
                                </button>
                            </div>
                        </div>
                        <div class="text-sm font-medium text-gray-400">{{ notification.message }}</div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

</main>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/notificationScript.js' %}"></script>
{% endblock %}

budgetbuddy/account/templates/sidebar.html
{% load static %}
{% load custom_filters %}

{% comment %} <body class="text-green-900 font-inter"> {% endcomment %}
    <!-- start: Sidebar -->
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
    <span class="sr-only">Open sidebar</span>
    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
    </svg>
</button>

<aside id="default-sidebar" class="fixed left-0 top-0 w-64 h-screen bg-green-700 p-4 transition-transform -translate-x-full md:translate-x-0 z-50" aria-label="Sidebar">
    <div class="fixed left-0 top-0 w-64 h-full bg-green-700 p-4">
        <a href="{% url 'home' %}" class="flex items-center pb-4 border-b border-b-green-600">
            <img src="{% static 'image/logo.jpg' %}" alt="" class="w-10 h-10 rounded object-cover">
            <span class="text-lg font-bold text-white ml-3">BudgetBuddy</span>
        </a>
        <ul class="mt-4">
            <li class="mb-1 {% if path == '/account/' %}group active{% endif %}">
                <a href="{% url 'home' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-home-2-line mr-3 text-xl"></i>
                    <span class="text-sm">Home</span>
                </a>
            </li>
            <li class="mb-1 {% if path|starts_with:'/account/transaction/' %}group active{% endif %}">
                <a href="{% url 'transaction' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-file-chart-line mr-3 text-xl"></i>
                    <span class="text-sm">Transaction</span>
                </a>
            </li>
            <li class="mb-1 {% if path|starts_with:'/account/budget/' %}group active{% endif %}">
                <a href="{% url 'budget' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-hand-coin-line mr-3 text-xl"></i>
                    <span class="text-sm">Budget</span>
                </a>
            </li>
            <li class="mb-1 {% if path|starts_with:'/account/saving/' %}group active{% endif %}">
                <a href="{% url 'saving' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-bank-line mr-3 text-xl"></i>
                    <span class="text-sm">Saving</span>
                </a>
            </li>
            <li class="mb-1 {% if path|starts_with:'/account/account/' %}group active{% endif %}">
                <a href="{% url 'account' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-file-user-line mr-3 text-xl"></i>
                    <span class="text-sm">Account</span>
                </a>
            </li>
            <li class="mb-1 {% if path|starts_with:'/account/notify/' %}group active{% endif %}">
                <a href="{% url 'notify' %}" class="flex items-center justify-between py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <div class="flex items-center">
                    <i class="ri-notification-line mr-3 text-xl"></i>
                    <span class="text-sm">Notify</span>
                    </div>
                    {% if numNotify != 0 %}
                        <span class="flex items-center justify-center bg-red-600 text-white h-5 w-5 text-xs font-bold rounded-full ">
                            {{ numNotify }}
                        </span>
                    {% endif %}
                </a>
            </li>
            {% if perms.account.view_category %}
            <li class="mb-1 {% if path|starts_with:'/account/developer/' %}group active{% endif %}">
                <a href="{% url 'categoriesDev' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-admin-line mr-3 text-xl"></i>
                    <span class="text-sm">Developer</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <ul class="absolute bottom-4 left-4">
            <li>
                <a href="{% url 'edit-profile' %}" class="flex items-center py-2 px-4 text-white hover:text-gray-300">
                    <i class="ri-settings-4-line mr-3 text-xl"></i>
                    <span class="text-sm">Setting</span>
                </a>
            </li>
            <li>
                <a href="{% url 'logout' %}" class="flex items-center py-2 px-4 text-white hover:text-black">
                    <i class="ri-logout-box-line mr-3 text-xl"></i>
                    <span class="text-sm">Log Out</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

<script src="{% static 'js/script.js' %}"></script>



            {% comment %} <li class="mb-1 group"></li>
                <a href="{% url 'transaction' %}" class="flex items-center py-2 px-4 text-white hover:bg-green-600 hover:text-gray-100 rounded-md group-[.active]:bg-green-900 group-[.active]:text-white">
                    <i class="ri-file-chart-line mr-3 text-xl"></i>
                    <span class="text-sm">Transaction</span>
                </a>
                <ul class="pl-8 mt-2 sidebar-menu">
                    <li class="mb-3">
                        <a href="#" class="text-white text-sm flex items-center hover:text-gray-100 before:contents-[' '] before:w-1 before:h-1 before:rounded-full before:bg-white before:mr-3">Income</a>
                    </li>
                    <li class="mb-3"></li>
                        <a href="#" class="text-white text-sm flex items-center hover:text-gray-100 before:contents-[' '] before:w-1 before:h-1 before:rounded-full before:bg-white before:mr-3">Expense</a>
                    </li>
                </ul>
            </li> {% endcomment %}